Added value check to init method
slackapi/python-slack-events-api pull request #91
Opened 2021-04-29 18:49 UTC by temurchichua

Added the value check to the init method.

###  Summary

I've set the env. variable for the Slack Event Token and used it to create Adapter as following:

```python
slack_event_adapter = SlackEventAdapter(os.environ.get("SLACK_EVENTS_TOKEN"), "/slack/events", app)
```

I made a typo while setting the variable, thus I was getting "Your URL didn't respond with the value of the challenge parameter." on the Event Subscription page with the following error in my terminal:

```bash
Traceback (most recent call last):
  File "D:\PycharmProjects\Slackbot\flipper\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\PycharmProjects\Slackbot\flipper\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\PycharmProjects\Slackbot\flipper\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\PycharmProjects\Slackbot\flipper\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\PycharmProjects\Slackbot\flipper\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\PycharmProjects\Slackbot\flipper\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PycharmProjects\Slackbot\flipper\venv\lib\site-packages\slackeventsapi\server.py", line 100, in event
    if req_signature is None or not self.verify_signature(req_timestamp, req_signature):
  File "D:\PycharmProjects\Slackbot\flipper\venv\lib\site-packages\slackeventsapi\server.py", line 60, in verify_signature
    str.encode(self.signing_secret),
TypeError: descriptor 'encode' for 'str' objects doesn't apply to a 'NoneType' object
```

I took some time to look through the source code and see what went wrong. I think value checking could come in handy for other developers to easily find the error in their project.

### Requirements (place an `x` in each `[ ]`)

* [X] I've read and understood the [Contributing guidelines](https://github.com/slackapi/python-slack-events-api/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).

2021-04-29 22:05 UTC, seratch commented
Hi @temurchichua, thanks for taking the time to make this pull request! We are happy to merge this improvement but I have a few comments. Can you check them when you have a chance?

2021-04-29 22:08 UTC, seratch requested changes

2021-04-29 22:08 UTC, seratch commented on .gitignore
> +venv/
I know you use `venv/` only but many people may use `.venv`. Can you add the following ones as well?
```suggestion
venv/
.venv/
.env/
```

2021-04-29 22:08 UTC, seratch commented on slackeventsapi/__init__.py
> +                             f'parameter.')
How about doing like this?
```suggestion
        if signing_secret is None:
            message = "signing_secret is required but you passed None in the first argument"
            raise ValueError(message)
        self.signing_secret = signing_secret
```

2021-05-01 08:49 UTC, temurchichua commented on .gitignore
> +venv/
That sounds right to me.

2021-05-01 08:50 UTC, temurchichua commented on slackeventsapi/__init__.py
> +                             f'parameter.')
Yes, that looks more Pythonic.

2021-05-01 08:54 UTC, temurchichua commented
@seratch thanks for reviewing the pull request.
Good points. I've included changes in the commit.

2021-05-01 09:15 UTC, seratch approved these changes
LGTM

2021-05-01 09:15 UTC, seratch commented
@temurchichua Thanks for the contribution!

2021-05-01 09:15 UTC, merged